#!/bin/sh

export XDG_CONFIG_DIRS="$HOME/.config/aerothemeplasma:/etc/xdg:$XDG_CONFIG_DIRS" 
export PLASMA_DEFAULT_SHELL=io.gitgud.wackyideas.desktop
/usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland
